# Generated by Django 4.2.15 on 2026-04-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('search_terms', models.TextField(help_text='Search query for arxiv/biorxiv APIs')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('arxiv', 'arXiv'), ('biorxiv', 'bioRxiv')], max_length=10)),
                ('source_id', models.CharField(help_text='e.g. arxiv ID like 2301.12345', max_length=100)),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('has_pdf', models.BooleanField(default=False)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('has_latex', models.BooleanField(default=False)),
                ('latex_path', models.CharField(blank=True, max_length=500)),
                ('dataset_links', models.JSONField(blank=True, default=list, help_text="List of dicts: [{'url': '...', 'description': '...'}]")),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='papers.topic')),
            ],
            options={
                'ordering': ['-published_date'],
                'unique_together': {('source', 'source_id', 'topic')},
            },
        ),
    ]
