# Generated by Django 4.2.15 on 2026-04-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='latex_url',
            field=models.URLField(blank=True, help_text='Direct link to LaTeX source', max_length=500),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Direct link to PDF', max_length=500),
        ),
    ]
