# Generated by Django 4.2.15 on 2026-04-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_latex_url_paper_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('paper_url', models.URLField(blank=True, help_text='Link to the paper (optional)', max_length=500)),
                ('latex_file', models.FileField(upload_to='uploads/latex/')),
                ('pdf_file', models.FileField(blank=True, upload_to='uploads/pdf/')),
                ('code_url', models.URLField(blank=True, help_text='Link to code repository (optional)', max_length=500)),
                ('dataset_url', models.URLField(blank=True, help_text='Link to dataset (optional)', max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='papers.topic')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
