# Generated by Django 4.2.15 on 2026-04-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paperupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='xml_path',
            field=models.CharField(blank=True, help_text='Path to LaTeXML-converted XML file', max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='source',
            field=models.CharField(choices=[('arxiv', 'arXiv'), ('biorxiv', 'bioRxiv'), ('upload', 'User Upload')], max_length=10),
        ),
    ]
